// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: proto/jellyfinv1/jellyfin.proto

package jellyfinv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RefreshLibraryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // optional; empty = full library refresh
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshLibraryRequest) Reset() {
	*x = RefreshLibraryRequest{}
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshLibraryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshLibraryRequest) ProtoMessage() {}

func (x *RefreshLibraryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshLibraryRequest.ProtoReflect.Descriptor instead.
func (*RefreshLibraryRequest) Descriptor() ([]byte, []int) {
	return file_proto_jellyfinv1_jellyfin_proto_rawDescGZIP(), []int{0}
}

func (x *RefreshLibraryRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type RefreshLibraryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshLibraryResponse) Reset() {
	*x = RefreshLibraryResponse{}
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshLibraryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshLibraryResponse) ProtoMessage() {}

func (x *RefreshLibraryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshLibraryResponse.ProtoReflect.Descriptor instead.
func (*RefreshLibraryResponse) Descriptor() ([]byte, []int) {
	return file_proto_jellyfinv1_jellyfin_proto_rawDescGZIP(), []int{1}
}

func (x *RefreshLibraryResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type PlayURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayURLRequest) Reset() {
	*x = PlayURLRequest{}
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayURLRequest) ProtoMessage() {}

func (x *PlayURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayURLRequest.ProtoReflect.Descriptor instead.
func (*PlayURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_jellyfinv1_jellyfin_proto_rawDescGZIP(), []int{2}
}

func (x *PlayURLRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type PlayURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayURLResponse) Reset() {
	*x = PlayURLResponse{}
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayURLResponse) ProtoMessage() {}

func (x *PlayURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayURLResponse.ProtoReflect.Descriptor instead.
func (*PlayURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_jellyfinv1_jellyfin_proto_rawDescGZIP(), []int{3}
}

func (x *PlayURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_jellyfinv1_jellyfin_proto_rawDescGZIP(), []int{4}
}

type StatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Configured          bool                   `protobuf:"varint,1,opt,name=configured,proto3" json:"configured,omitempty"`
	BaseUrl             string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ConflictMode        string                 `protobuf:"bytes,3,opt,name=conflict_mode,json=conflictMode,proto3" json:"conflict_mode,omitempty"`
	ItemLinks           int32                  `protobuf:"varint,4,opt,name=item_links,json=itemLinks,proto3" json:"item_links,omitempty"`
	SessionsPollEnabled bool                   `protobuf:"varint,5,opt,name=sessions_poll_enabled,json=sessionsPollEnabled,proto3" json:"sessions_poll_enabled,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_jellyfinv1_jellyfin_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

func (x *StatusResponse) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *StatusResponse) GetConflictMode() string {
	if x != nil {
		return x.ConflictMode
	}
	return ""
}

func (x *StatusResponse) GetItemLinks() int32 {
	if x != nil {
		return x.ItemLinks
	}
	return 0
}

func (x *StatusResponse) GetSessionsPollEnabled() bool {
	if x != nil {
		return x.SessionsPollEnabled
	}
	return false
}

type ItemLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MuxcoreId     string                 `protobuf:"bytes,1,opt,name=muxcore_id,json=muxcoreId,proto3" json:"muxcore_id,omitempty"`
	JellyfinId    string                 `protobuf:"bytes,2,opt,name=jellyfin_id,json=jellyfinId,proto3" json:"jellyfin_id,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	ProviderIds   map[string]string      `protobuf:"bytes,4,rep,name=provider_ids,json=providerIds,proto3" json:"provider_ids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MediaKind     string                 `protobuf:"bytes,5,opt,name=media_kind,json=mediaKind,proto3" json:"media_kind,omitempty"` // movie | tv | episode | other
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	UpdatedAtUnix int64                  `protobuf:"varint,7,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemLink) Reset() {
	*x = ItemLink{}
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemLink) ProtoMessage() {}

func (x *ItemLink) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemLink.ProtoReflect.Descriptor instead.
func (*ItemLink) Descriptor() ([]byte, []int) {
	return file_proto_jellyfinv1_jellyfin_proto_rawDescGZIP(), []int{6}
}

func (x *ItemLink) GetMuxcoreId() string {
	if x != nil {
		return x.MuxcoreId
	}
	return ""
}

func (x *ItemLink) GetJellyfinId() string {
	if x != nil {
		return x.JellyfinId
	}
	return ""
}

func (x *ItemLink) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ItemLink) GetProviderIds() map[string]string {
	if x != nil {
		return x.ProviderIds
	}
	return nil
}

func (x *ItemLink) GetMediaKind() string {
	if x != nil {
		return x.MediaKind
	}
	return ""
}

func (x *ItemLink) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ItemLink) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

type ListItemLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaKind     string                 `protobuf:"bytes,1,opt,name=media_kind,json=mediaKind,proto3" json:"media_kind,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemLinksRequest) Reset() {
	*x = ListItemLinksRequest{}
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemLinksRequest) ProtoMessage() {}

func (x *ListItemLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemLinksRequest.ProtoReflect.Descriptor instead.
func (*ListItemLinksRequest) Descriptor() ([]byte, []int) {
	return file_proto_jellyfinv1_jellyfin_proto_rawDescGZIP(), []int{7}
}

func (x *ListItemLinksRequest) GetMediaKind() string {
	if x != nil {
		return x.MediaKind
	}
	return ""
}

type ListItemLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*ItemLink            `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemLinksResponse) Reset() {
	*x = ListItemLinksResponse{}
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemLinksResponse) ProtoMessage() {}

func (x *ListItemLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemLinksResponse.ProtoReflect.Descriptor instead.
func (*ListItemLinksResponse) Descriptor() ([]byte, []int) {
	return file_proto_jellyfinv1_jellyfin_proto_rawDescGZIP(), []int{8}
}

func (x *ListItemLinksResponse) GetLinks() []*ItemLink {
	if x != nil {
		return x.Links
	}
	return nil
}

type UpsertItemLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *ItemLink              `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertItemLinkRequest) Reset() {
	*x = UpsertItemLinkRequest{}
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertItemLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertItemLinkRequest) ProtoMessage() {}

func (x *UpsertItemLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertItemLinkRequest.ProtoReflect.Descriptor instead.
func (*UpsertItemLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_jellyfinv1_jellyfin_proto_rawDescGZIP(), []int{9}
}

func (x *UpsertItemLinkRequest) GetLink() *ItemLink {
	if x != nil {
		return x.Link
	}
	return nil
}

type UpsertItemLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *ItemLink              `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertItemLinkResponse) Reset() {
	*x = UpsertItemLinkResponse{}
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertItemLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertItemLinkResponse) ProtoMessage() {}

func (x *UpsertItemLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertItemLinkResponse.ProtoReflect.Descriptor instead.
func (*UpsertItemLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_jellyfinv1_jellyfin_proto_rawDescGZIP(), []int{10}
}

func (x *UpsertItemLinkResponse) GetLink() *ItemLink {
	if x != nil {
		return x.Link
	}
	return nil
}

type DeleteItemLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MuxcoreId     string                 `protobuf:"bytes,1,opt,name=muxcore_id,json=muxcoreId,proto3" json:"muxcore_id,omitempty"`
	JellyfinId    string                 `protobuf:"bytes,2,opt,name=jellyfin_id,json=jellyfinId,proto3" json:"jellyfin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemLinkRequest) Reset() {
	*x = DeleteItemLinkRequest{}
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemLinkRequest) ProtoMessage() {}

func (x *DeleteItemLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemLinkRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_jellyfinv1_jellyfin_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteItemLinkRequest) GetMuxcoreId() string {
	if x != nil {
		return x.MuxcoreId
	}
	return ""
}

func (x *DeleteItemLinkRequest) GetJellyfinId() string {
	if x != nil {
		return x.JellyfinId
	}
	return ""
}

type DeleteItemLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemLinkResponse) Reset() {
	*x = DeleteItemLinkResponse{}
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemLinkResponse) ProtoMessage() {}

func (x *DeleteItemLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemLinkResponse.ProtoReflect.Descriptor instead.
func (*DeleteItemLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_jellyfinv1_jellyfin_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteItemLinkResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type MatchItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MuxcoreId     string                 `protobuf:"bytes,1,opt,name=muxcore_id,json=muxcoreId,proto3" json:"muxcore_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	ProviderIds   map[string]string      `protobuf:"bytes,3,rep,name=provider_ids,json=providerIds,proto3" json:"provider_ids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MediaKind     string                 `protobuf:"bytes,4,opt,name=media_kind,json=mediaKind,proto3" json:"media_kind,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchItemRequest) Reset() {
	*x = MatchItemRequest{}
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchItemRequest) ProtoMessage() {}

func (x *MatchItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchItemRequest.ProtoReflect.Descriptor instead.
func (*MatchItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_jellyfinv1_jellyfin_proto_rawDescGZIP(), []int{13}
}

func (x *MatchItemRequest) GetMuxcoreId() string {
	if x != nil {
		return x.MuxcoreId
	}
	return ""
}

func (x *MatchItemRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MatchItemRequest) GetProviderIds() map[string]string {
	if x != nil {
		return x.ProviderIds
	}
	return nil
}

func (x *MatchItemRequest) GetMediaKind() string {
	if x != nil {
		return x.MediaKind
	}
	return ""
}

func (x *MatchItemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type MatchItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *ItemLink              `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Matched       bool                   `protobuf:"varint,2,opt,name=matched,proto3" json:"matched,omitempty"`
	MatchReason   string                 `protobuf:"bytes,3,opt,name=match_reason,json=matchReason,proto3" json:"match_reason,omitempty"` // provider_id | path | existing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchItemResponse) Reset() {
	*x = MatchItemResponse{}
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchItemResponse) ProtoMessage() {}

func (x *MatchItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchItemResponse.ProtoReflect.Descriptor instead.
func (*MatchItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_jellyfinv1_jellyfin_proto_rawDescGZIP(), []int{14}
}

func (x *MatchItemResponse) GetLink() *ItemLink {
	if x != nil {
		return x.Link
	}
	return nil
}

func (x *MatchItemResponse) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *MatchItemResponse) GetMatchReason() string {
	if x != nil {
		return x.MatchReason
	}
	return ""
}

type SyncLibraryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// jellyfin = pull Jellyfin → update links (Jellyfin authoritative for metadata)
	// muxcore = push known links / match MuxCore IDs against Jellyfin
	// both = pull then reconcile by conflict_mode
	Direction     string `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"`
	DryRun        bool   `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncLibraryRequest) Reset() {
	*x = SyncLibraryRequest{}
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncLibraryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncLibraryRequest) ProtoMessage() {}

func (x *SyncLibraryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncLibraryRequest.ProtoReflect.Descriptor instead.
func (*SyncLibraryRequest) Descriptor() ([]byte, []int) {
	return file_proto_jellyfinv1_jellyfin_proto_rawDescGZIP(), []int{15}
}

func (x *SyncLibraryRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *SyncLibraryRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type SyncLibraryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scanned       int32                  `protobuf:"varint,1,opt,name=scanned,proto3" json:"scanned,omitempty"`
	Matched       int32                  `protobuf:"varint,2,opt,name=matched,proto3" json:"matched,omitempty"`
	Upserted      int32                  `protobuf:"varint,3,opt,name=upserted,proto3" json:"upserted,omitempty"`
	Removed       int32                  `protobuf:"varint,4,opt,name=removed,proto3" json:"removed,omitempty"`
	Errors        []string               `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncLibraryResponse) Reset() {
	*x = SyncLibraryResponse{}
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncLibraryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncLibraryResponse) ProtoMessage() {}

func (x *SyncLibraryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncLibraryResponse.ProtoReflect.Descriptor instead.
func (*SyncLibraryResponse) Descriptor() ([]byte, []int) {
	return file_proto_jellyfinv1_jellyfin_proto_rawDescGZIP(), []int{16}
}

func (x *SyncLibraryResponse) GetScanned() int32 {
	if x != nil {
		return x.Scanned
	}
	return 0
}

func (x *SyncLibraryResponse) GetMatched() int32 {
	if x != nil {
		return x.Matched
	}
	return 0
}

func (x *SyncLibraryResponse) GetUpserted() int32 {
	if x != nil {
		return x.Upserted
	}
	return 0
}

func (x *SyncLibraryResponse) GetRemoved() int32 {
	if x != nil {
		return x.Removed
	}
	return 0
}

func (x *SyncLibraryResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type TerminateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateSessionRequest) Reset() {
	*x = TerminateSessionRequest{}
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateSessionRequest) ProtoMessage() {}

func (x *TerminateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateSessionRequest.ProtoReflect.Descriptor instead.
func (*TerminateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_jellyfinv1_jellyfin_proto_rawDescGZIP(), []int{17}
}

func (x *TerminateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminateSessionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TerminateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateSessionResponse) Reset() {
	*x = TerminateSessionResponse{}
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateSessionResponse) ProtoMessage() {}

func (x *TerminateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jellyfinv1_jellyfin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateSessionResponse.ProtoReflect.Descriptor instead.
func (*TerminateSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_jellyfinv1_jellyfin_proto_rawDescGZIP(), []int{18}
}

func (x *TerminateSessionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TerminateSessionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_jellyfinv1_jellyfin_proto protoreflect.FileDescriptor

const file_proto_jellyfinv1_jellyfin_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/jellyfinv1/jellyfin.proto\x12\x1cmuxcore.playback.jellyfin.v1\"0\n" +
	"\x15RefreshLibraryRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\"(\n" +
	"\x16RefreshLibraryResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\")\n" +
	"\x0ePlayURLRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\"#\n" +
	"\x0fPlayURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x0f\n" +
	"\rStatusRequest\"\xc3\x01\n" +
	"\x0eStatusResponse\x12\x1e\n" +
	"\n" +
	"configured\x18\x01 \x01(\bR\n" +
	"configured\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12#\n" +
	"\rconflict_mode\x18\x03 \x01(\tR\fconflictMode\x12\x1d\n" +
	"\n" +
	"item_links\x18\x04 \x01(\x05R\titemLinks\x122\n" +
	"\x15sessions_poll_enabled\x18\x05 \x01(\bR\x13sessionsPollEnabled\"\xd7\x02\n" +
	"\bItemLink\x12\x1d\n" +
	"\n" +
	"muxcore_id\x18\x01 \x01(\tR\tmuxcoreId\x12\x1f\n" +
	"\vjellyfin_id\x18\x02 \x01(\tR\n" +
	"jellyfinId\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12Z\n" +
	"\fprovider_ids\x18\x04 \x03(\v27.muxcore.playback.jellyfin.v1.ItemLink.ProviderIdsEntryR\vproviderIds\x12\x1d\n" +
	"\n" +
	"media_kind\x18\x05 \x01(\tR\tmediaKind\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12&\n" +
	"\x0fupdated_at_unix\x18\a \x01(\x03R\rupdatedAtUnix\x1a>\n" +
	"\x10ProviderIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\x14ListItemLinksRequest\x12\x1d\n" +
	"\n" +
	"media_kind\x18\x01 \x01(\tR\tmediaKind\"U\n" +
	"\x15ListItemLinksResponse\x12<\n" +
	"\x05links\x18\x01 \x03(\v2&.muxcore.playback.jellyfin.v1.ItemLinkR\x05links\"S\n" +
	"\x15UpsertItemLinkRequest\x12:\n" +
	"\x04link\x18\x01 \x01(\v2&.muxcore.playback.jellyfin.v1.ItemLinkR\x04link\"T\n" +
	"\x16UpsertItemLinkResponse\x12:\n" +
	"\x04link\x18\x01 \x01(\v2&.muxcore.playback.jellyfin.v1.ItemLinkR\x04link\"W\n" +
	"\x15DeleteItemLinkRequest\x12\x1d\n" +
	"\n" +
	"muxcore_id\x18\x01 \x01(\tR\tmuxcoreId\x12\x1f\n" +
	"\vjellyfin_id\x18\x02 \x01(\tR\n" +
	"jellyfinId\"(\n" +
	"\x16DeleteItemLinkResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x9e\x02\n" +
	"\x10MatchItemRequest\x12\x1d\n" +
	"\n" +
	"muxcore_id\x18\x01 \x01(\tR\tmuxcoreId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12b\n" +
	"\fprovider_ids\x18\x03 \x03(\v2?.muxcore.playback.jellyfin.v1.MatchItemRequest.ProviderIdsEntryR\vproviderIds\x12\x1d\n" +
	"\n" +
	"media_kind\x18\x04 \x01(\tR\tmediaKind\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x1a>\n" +
	"\x10ProviderIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x01\n" +
	"\x11MatchItemResponse\x12:\n" +
	"\x04link\x18\x01 \x01(\v2&.muxcore.playback.jellyfin.v1.ItemLinkR\x04link\x12\x18\n" +
	"\amatched\x18\x02 \x01(\bR\amatched\x12!\n" +
	"\fmatch_reason\x18\x03 \x01(\tR\vmatchReason\"K\n" +
	"\x12SyncLibraryRequest\x12\x1c\n" +
	"\tdirection\x18\x01 \x01(\tR\tdirection\x12\x17\n" +
	"\adry_run\x18\x02 \x01(\bR\x06dryRun\"\x97\x01\n" +
	"\x13SyncLibraryResponse\x12\x18\n" +
	"\ascanned\x18\x01 \x01(\x05R\ascanned\x12\x18\n" +
	"\amatched\x18\x02 \x01(\x05R\amatched\x12\x1a\n" +
	"\bupserted\x18\x03 \x01(\x05R\bupserted\x12\x18\n" +
	"\aremoved\x18\x04 \x01(\x05R\aremoved\x12\x16\n" +
	"\x06errors\x18\x05 \x03(\tR\x06errors\"P\n" +
	"\x17TerminateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"@\n" +
	"\x18TerminateSessionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xb4\b\n" +
	"\x0eJellyfinBridge\x12{\n" +
	"\x0eRefreshLibrary\x123.muxcore.playback.jellyfin.v1.RefreshLibraryRequest\x1a4.muxcore.playback.jellyfin.v1.RefreshLibraryResponse\x12f\n" +
	"\aPlayURL\x12,.muxcore.playback.jellyfin.v1.PlayURLRequest\x1a-.muxcore.playback.jellyfin.v1.PlayURLResponse\x12c\n" +
	"\x06Status\x12+.muxcore.playback.jellyfin.v1.StatusRequest\x1a,.muxcore.playback.jellyfin.v1.StatusResponse\x12x\n" +
	"\rListItemLinks\x122.muxcore.playback.jellyfin.v1.ListItemLinksRequest\x1a3.muxcore.playback.jellyfin.v1.ListItemLinksResponse\x12{\n" +
	"\x0eUpsertItemLink\x123.muxcore.playback.jellyfin.v1.UpsertItemLinkRequest\x1a4.muxcore.playback.jellyfin.v1.UpsertItemLinkResponse\x12{\n" +
	"\x0eDeleteItemLink\x123.muxcore.playback.jellyfin.v1.DeleteItemLinkRequest\x1a4.muxcore.playback.jellyfin.v1.DeleteItemLinkResponse\x12l\n" +
	"\tMatchItem\x12..muxcore.playback.jellyfin.v1.MatchItemRequest\x1a/.muxcore.playback.jellyfin.v1.MatchItemResponse\x12r\n" +
	"\vSyncLibrary\x120.muxcore.playback.jellyfin.v1.SyncLibraryRequest\x1a1.muxcore.playback.jellyfin.v1.SyncLibraryResponse\x12\x81\x01\n" +
	"\x10TerminateSession\x125.muxcore.playback.jellyfin.v1.TerminateSessionRequest\x1a6.muxcore.playback.jellyfin.v1.TerminateSessionResponseB?Z=github.com/Muxcore-Media/jellyfin/proto/jellyfinv1;jellyfinv1b\x06proto3"

var (
	file_proto_jellyfinv1_jellyfin_proto_rawDescOnce sync.Once
	file_proto_jellyfinv1_jellyfin_proto_rawDescData []byte
)

func file_proto_jellyfinv1_jellyfin_proto_rawDescGZIP() []byte {
	file_proto_jellyfinv1_jellyfin_proto_rawDescOnce.Do(func() {
		file_proto_jellyfinv1_jellyfin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_jellyfinv1_jellyfin_proto_rawDesc), len(file_proto_jellyfinv1_jellyfin_proto_rawDesc)))
	})
	return file_proto_jellyfinv1_jellyfin_proto_rawDescData
}

var file_proto_jellyfinv1_jellyfin_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_jellyfinv1_jellyfin_proto_goTypes = []any{
	(*RefreshLibraryRequest)(nil),    // 0: muxcore.playback.jellyfin.v1.RefreshLibraryRequest
	(*RefreshLibraryResponse)(nil),   // 1: muxcore.playback.jellyfin.v1.RefreshLibraryResponse
	(*PlayURLRequest)(nil),           // 2: muxcore.playback.jellyfin.v1.PlayURLRequest
	(*PlayURLResponse)(nil),          // 3: muxcore.playback.jellyfin.v1.PlayURLResponse
	(*StatusRequest)(nil),            // 4: muxcore.playback.jellyfin.v1.StatusRequest
	(*StatusResponse)(nil),           // 5: muxcore.playback.jellyfin.v1.StatusResponse
	(*ItemLink)(nil),                 // 6: muxcore.playback.jellyfin.v1.ItemLink
	(*ListItemLinksRequest)(nil),     // 7: muxcore.playback.jellyfin.v1.ListItemLinksRequest
	(*ListItemLinksResponse)(nil),    // 8: muxcore.playback.jellyfin.v1.ListItemLinksResponse
	(*UpsertItemLinkRequest)(nil),    // 9: muxcore.playback.jellyfin.v1.UpsertItemLinkRequest
	(*UpsertItemLinkResponse)(nil),   // 10: muxcore.playback.jellyfin.v1.UpsertItemLinkResponse
	(*DeleteItemLinkRequest)(nil),    // 11: muxcore.playback.jellyfin.v1.DeleteItemLinkRequest
	(*DeleteItemLinkResponse)(nil),   // 12: muxcore.playback.jellyfin.v1.DeleteItemLinkResponse
	(*MatchItemRequest)(nil),         // 13: muxcore.playback.jellyfin.v1.MatchItemRequest
	(*MatchItemResponse)(nil),        // 14: muxcore.playback.jellyfin.v1.MatchItemResponse
	(*SyncLibraryRequest)(nil),       // 15: muxcore.playback.jellyfin.v1.SyncLibraryRequest
	(*SyncLibraryResponse)(nil),      // 16: muxcore.playback.jellyfin.v1.SyncLibraryResponse
	(*TerminateSessionRequest)(nil),  // 17: muxcore.playback.jellyfin.v1.TerminateSessionRequest
	(*TerminateSessionResponse)(nil), // 18: muxcore.playback.jellyfin.v1.TerminateSessionResponse
	nil,                              // 19: muxcore.playback.jellyfin.v1.ItemLink.ProviderIdsEntry
	nil,                              // 20: muxcore.playback.jellyfin.v1.MatchItemRequest.ProviderIdsEntry
}
var file_proto_jellyfinv1_jellyfin_proto_depIdxs = []int32{
	19, // 0: muxcore.playback.jellyfin.v1.ItemLink.provider_ids:type_name -> muxcore.playback.jellyfin.v1.ItemLink.ProviderIdsEntry
	6,  // 1: muxcore.playback.jellyfin.v1.ListItemLinksResponse.links:type_name -> muxcore.playback.jellyfin.v1.ItemLink
	6,  // 2: muxcore.playback.jellyfin.v1.UpsertItemLinkRequest.link:type_name -> muxcore.playback.jellyfin.v1.ItemLink
	6,  // 3: muxcore.playback.jellyfin.v1.UpsertItemLinkResponse.link:type_name -> muxcore.playback.jellyfin.v1.ItemLink
	20, // 4: muxcore.playback.jellyfin.v1.MatchItemRequest.provider_ids:type_name -> muxcore.playback.jellyfin.v1.MatchItemRequest.ProviderIdsEntry
	6,  // 5: muxcore.playback.jellyfin.v1.MatchItemResponse.link:type_name -> muxcore.playback.jellyfin.v1.ItemLink
	0,  // 6: muxcore.playback.jellyfin.v1.JellyfinBridge.RefreshLibrary:input_type -> muxcore.playback.jellyfin.v1.RefreshLibraryRequest
	2,  // 7: muxcore.playback.jellyfin.v1.JellyfinBridge.PlayURL:input_type -> muxcore.playback.jellyfin.v1.PlayURLRequest
	4,  // 8: muxcore.playback.jellyfin.v1.JellyfinBridge.Status:input_type -> muxcore.playback.jellyfin.v1.StatusRequest
	7,  // 9: muxcore.playback.jellyfin.v1.JellyfinBridge.ListItemLinks:input_type -> muxcore.playback.jellyfin.v1.ListItemLinksRequest
	9,  // 10: muxcore.playback.jellyfin.v1.JellyfinBridge.UpsertItemLink:input_type -> muxcore.playback.jellyfin.v1.UpsertItemLinkRequest
	11, // 11: muxcore.playback.jellyfin.v1.JellyfinBridge.DeleteItemLink:input_type -> muxcore.playback.jellyfin.v1.DeleteItemLinkRequest
	13, // 12: muxcore.playback.jellyfin.v1.JellyfinBridge.MatchItem:input_type -> muxcore.playback.jellyfin.v1.MatchItemRequest
	15, // 13: muxcore.playback.jellyfin.v1.JellyfinBridge.SyncLibrary:input_type -> muxcore.playback.jellyfin.v1.SyncLibraryRequest
	17, // 14: muxcore.playback.jellyfin.v1.JellyfinBridge.TerminateSession:input_type -> muxcore.playback.jellyfin.v1.TerminateSessionRequest
	1,  // 15: muxcore.playback.jellyfin.v1.JellyfinBridge.RefreshLibrary:output_type -> muxcore.playback.jellyfin.v1.RefreshLibraryResponse
	3,  // 16: muxcore.playback.jellyfin.v1.JellyfinBridge.PlayURL:output_type -> muxcore.playback.jellyfin.v1.PlayURLResponse
	5,  // 17: muxcore.playback.jellyfin.v1.JellyfinBridge.Status:output_type -> muxcore.playback.jellyfin.v1.StatusResponse
	8,  // 18: muxcore.playback.jellyfin.v1.JellyfinBridge.ListItemLinks:output_type -> muxcore.playback.jellyfin.v1.ListItemLinksResponse
	10, // 19: muxcore.playback.jellyfin.v1.JellyfinBridge.UpsertItemLink:output_type -> muxcore.playback.jellyfin.v1.UpsertItemLinkResponse
	12, // 20: muxcore.playback.jellyfin.v1.JellyfinBridge.DeleteItemLink:output_type -> muxcore.playback.jellyfin.v1.DeleteItemLinkResponse
	14, // 21: muxcore.playback.jellyfin.v1.JellyfinBridge.MatchItem:output_type -> muxcore.playback.jellyfin.v1.MatchItemResponse
	16, // 22: muxcore.playback.jellyfin.v1.JellyfinBridge.SyncLibrary:output_type -> muxcore.playback.jellyfin.v1.SyncLibraryResponse
	18, // 23: muxcore.playback.jellyfin.v1.JellyfinBridge.TerminateSession:output_type -> muxcore.playback.jellyfin.v1.TerminateSessionResponse
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_jellyfinv1_jellyfin_proto_init() }
func file_proto_jellyfinv1_jellyfin_proto_init() {
	if File_proto_jellyfinv1_jellyfin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_jellyfinv1_jellyfin_proto_rawDesc), len(file_proto_jellyfinv1_jellyfin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_jellyfinv1_jellyfin_proto_goTypes,
		DependencyIndexes: file_proto_jellyfinv1_jellyfin_proto_depIdxs,
		MessageInfos:      file_proto_jellyfinv1_jellyfin_proto_msgTypes,
	}.Build()
	File_proto_jellyfinv1_jellyfin_proto = out.File
	file_proto_jellyfinv1_jellyfin_proto_goTypes = nil
	file_proto_jellyfinv1_jellyfin_proto_depIdxs = nil
}
