// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: proto/jellyfinv1/jellyfin.proto

package jellyfinv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JellyfinBridge_RefreshLibrary_FullMethodName   = "/muxcore.playback.jellyfin.v1.JellyfinBridge/RefreshLibrary"
	JellyfinBridge_PlayURL_FullMethodName          = "/muxcore.playback.jellyfin.v1.JellyfinBridge/PlayURL"
	JellyfinBridge_Status_FullMethodName           = "/muxcore.playback.jellyfin.v1.JellyfinBridge/Status"
	JellyfinBridge_ListItemLinks_FullMethodName    = "/muxcore.playback.jellyfin.v1.JellyfinBridge/ListItemLinks"
	JellyfinBridge_UpsertItemLink_FullMethodName   = "/muxcore.playback.jellyfin.v1.JellyfinBridge/UpsertItemLink"
	JellyfinBridge_DeleteItemLink_FullMethodName   = "/muxcore.playback.jellyfin.v1.JellyfinBridge/DeleteItemLink"
	JellyfinBridge_MatchItem_FullMethodName        = "/muxcore.playback.jellyfin.v1.JellyfinBridge/MatchItem"
	JellyfinBridge_SyncLibrary_FullMethodName      = "/muxcore.playback.jellyfin.v1.JellyfinBridge/SyncLibrary"
	JellyfinBridge_ListSessions_FullMethodName     = "/muxcore.playback.jellyfin.v1.JellyfinBridge/ListSessions"
	JellyfinBridge_TerminateSession_FullMethodName = "/muxcore.playback.jellyfin.v1.JellyfinBridge/TerminateSession"
)

// JellyfinBridgeClient is the client API for JellyfinBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JellyfinBridgeClient interface {
	RefreshLibrary(ctx context.Context, in *RefreshLibraryRequest, opts ...grpc.CallOption) (*RefreshLibraryResponse, error)
	PlayURL(ctx context.Context, in *PlayURLRequest, opts ...grpc.CallOption) (*PlayURLResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	ListItemLinks(ctx context.Context, in *ListItemLinksRequest, opts ...grpc.CallOption) (*ListItemLinksResponse, error)
	UpsertItemLink(ctx context.Context, in *UpsertItemLinkRequest, opts ...grpc.CallOption) (*UpsertItemLinkResponse, error)
	DeleteItemLink(ctx context.Context, in *DeleteItemLinkRequest, opts ...grpc.CallOption) (*DeleteItemLinkResponse, error)
	MatchItem(ctx context.Context, in *MatchItemRequest, opts ...grpc.CallOption) (*MatchItemResponse, error)
	SyncLibrary(ctx context.Context, in *SyncLibraryRequest, opts ...grpc.CallOption) (*SyncLibraryResponse, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	TerminateSession(ctx context.Context, in *TerminateSessionRequest, opts ...grpc.CallOption) (*TerminateSessionResponse, error)
}

type jellyfinBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewJellyfinBridgeClient(cc grpc.ClientConnInterface) JellyfinBridgeClient {
	return &jellyfinBridgeClient{cc}
}

func (c *jellyfinBridgeClient) RefreshLibrary(ctx context.Context, in *RefreshLibraryRequest, opts ...grpc.CallOption) (*RefreshLibraryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshLibraryResponse)
	err := c.cc.Invoke(ctx, JellyfinBridge_RefreshLibrary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jellyfinBridgeClient) PlayURL(ctx context.Context, in *PlayURLRequest, opts ...grpc.CallOption) (*PlayURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayURLResponse)
	err := c.cc.Invoke(ctx, JellyfinBridge_PlayURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jellyfinBridgeClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, JellyfinBridge_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jellyfinBridgeClient) ListItemLinks(ctx context.Context, in *ListItemLinksRequest, opts ...grpc.CallOption) (*ListItemLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListItemLinksResponse)
	err := c.cc.Invoke(ctx, JellyfinBridge_ListItemLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jellyfinBridgeClient) UpsertItemLink(ctx context.Context, in *UpsertItemLinkRequest, opts ...grpc.CallOption) (*UpsertItemLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertItemLinkResponse)
	err := c.cc.Invoke(ctx, JellyfinBridge_UpsertItemLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jellyfinBridgeClient) DeleteItemLink(ctx context.Context, in *DeleteItemLinkRequest, opts ...grpc.CallOption) (*DeleteItemLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteItemLinkResponse)
	err := c.cc.Invoke(ctx, JellyfinBridge_DeleteItemLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jellyfinBridgeClient) MatchItem(ctx context.Context, in *MatchItemRequest, opts ...grpc.CallOption) (*MatchItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchItemResponse)
	err := c.cc.Invoke(ctx, JellyfinBridge_MatchItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jellyfinBridgeClient) SyncLibrary(ctx context.Context, in *SyncLibraryRequest, opts ...grpc.CallOption) (*SyncLibraryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncLibraryResponse)
	err := c.cc.Invoke(ctx, JellyfinBridge_SyncLibrary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jellyfinBridgeClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, JellyfinBridge_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jellyfinBridgeClient) TerminateSession(ctx context.Context, in *TerminateSessionRequest, opts ...grpc.CallOption) (*TerminateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateSessionResponse)
	err := c.cc.Invoke(ctx, JellyfinBridge_TerminateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JellyfinBridgeServer is the server API for JellyfinBridge service.
// All implementations must embed UnimplementedJellyfinBridgeServer
// for forward compatibility.
type JellyfinBridgeServer interface {
	RefreshLibrary(context.Context, *RefreshLibraryRequest) (*RefreshLibraryResponse, error)
	PlayURL(context.Context, *PlayURLRequest) (*PlayURLResponse, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	ListItemLinks(context.Context, *ListItemLinksRequest) (*ListItemLinksResponse, error)
	UpsertItemLink(context.Context, *UpsertItemLinkRequest) (*UpsertItemLinkResponse, error)
	DeleteItemLink(context.Context, *DeleteItemLinkRequest) (*DeleteItemLinkResponse, error)
	MatchItem(context.Context, *MatchItemRequest) (*MatchItemResponse, error)
	SyncLibrary(context.Context, *SyncLibraryRequest) (*SyncLibraryResponse, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	TerminateSession(context.Context, *TerminateSessionRequest) (*TerminateSessionResponse, error)
	mustEmbedUnimplementedJellyfinBridgeServer()
}

// UnimplementedJellyfinBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJellyfinBridgeServer struct{}

func (UnimplementedJellyfinBridgeServer) RefreshLibrary(context.Context, *RefreshLibraryRequest) (*RefreshLibraryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshLibrary not implemented")
}
func (UnimplementedJellyfinBridgeServer) PlayURL(context.Context, *PlayURLRequest) (*PlayURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayURL not implemented")
}
func (UnimplementedJellyfinBridgeServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedJellyfinBridgeServer) ListItemLinks(context.Context, *ListItemLinksRequest) (*ListItemLinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListItemLinks not implemented")
}
func (UnimplementedJellyfinBridgeServer) UpsertItemLink(context.Context, *UpsertItemLinkRequest) (*UpsertItemLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertItemLink not implemented")
}
func (UnimplementedJellyfinBridgeServer) DeleteItemLink(context.Context, *DeleteItemLinkRequest) (*DeleteItemLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteItemLink not implemented")
}
func (UnimplementedJellyfinBridgeServer) MatchItem(context.Context, *MatchItemRequest) (*MatchItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MatchItem not implemented")
}
func (UnimplementedJellyfinBridgeServer) SyncLibrary(context.Context, *SyncLibraryRequest) (*SyncLibraryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncLibrary not implemented")
}
func (UnimplementedJellyfinBridgeServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedJellyfinBridgeServer) TerminateSession(context.Context, *TerminateSessionRequest) (*TerminateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TerminateSession not implemented")
}
func (UnimplementedJellyfinBridgeServer) mustEmbedUnimplementedJellyfinBridgeServer() {}
func (UnimplementedJellyfinBridgeServer) testEmbeddedByValue()                        {}

// UnsafeJellyfinBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JellyfinBridgeServer will
// result in compilation errors.
type UnsafeJellyfinBridgeServer interface {
	mustEmbedUnimplementedJellyfinBridgeServer()
}

func RegisterJellyfinBridgeServer(s grpc.ServiceRegistrar, srv JellyfinBridgeServer) {
	// If the following call pancis, it indicates UnimplementedJellyfinBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JellyfinBridge_ServiceDesc, srv)
}

func _JellyfinBridge_RefreshLibrary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshLibraryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JellyfinBridgeServer).RefreshLibrary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JellyfinBridge_RefreshLibrary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JellyfinBridgeServer).RefreshLibrary(ctx, req.(*RefreshLibraryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JellyfinBridge_PlayURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JellyfinBridgeServer).PlayURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JellyfinBridge_PlayURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JellyfinBridgeServer).PlayURL(ctx, req.(*PlayURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JellyfinBridge_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JellyfinBridgeServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JellyfinBridge_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JellyfinBridgeServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JellyfinBridge_ListItemLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListItemLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JellyfinBridgeServer).ListItemLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JellyfinBridge_ListItemLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JellyfinBridgeServer).ListItemLinks(ctx, req.(*ListItemLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JellyfinBridge_UpsertItemLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertItemLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JellyfinBridgeServer).UpsertItemLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JellyfinBridge_UpsertItemLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JellyfinBridgeServer).UpsertItemLink(ctx, req.(*UpsertItemLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JellyfinBridge_DeleteItemLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteItemLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JellyfinBridgeServer).DeleteItemLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JellyfinBridge_DeleteItemLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JellyfinBridgeServer).DeleteItemLink(ctx, req.(*DeleteItemLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JellyfinBridge_MatchItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JellyfinBridgeServer).MatchItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JellyfinBridge_MatchItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JellyfinBridgeServer).MatchItem(ctx, req.(*MatchItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JellyfinBridge_SyncLibrary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncLibraryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JellyfinBridgeServer).SyncLibrary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JellyfinBridge_SyncLibrary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JellyfinBridgeServer).SyncLibrary(ctx, req.(*SyncLibraryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JellyfinBridge_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JellyfinBridgeServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JellyfinBridge_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JellyfinBridgeServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JellyfinBridge_TerminateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JellyfinBridgeServer).TerminateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JellyfinBridge_TerminateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JellyfinBridgeServer).TerminateSession(ctx, req.(*TerminateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JellyfinBridge_ServiceDesc is the grpc.ServiceDesc for JellyfinBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JellyfinBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "muxcore.playback.jellyfin.v1.JellyfinBridge",
	HandlerType: (*JellyfinBridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RefreshLibrary",
			Handler:    _JellyfinBridge_RefreshLibrary_Handler,
		},
		{
			MethodName: "PlayURL",
			Handler:    _JellyfinBridge_PlayURL_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _JellyfinBridge_Status_Handler,
		},
		{
			MethodName: "ListItemLinks",
			Handler:    _JellyfinBridge_ListItemLinks_Handler,
		},
		{
			MethodName: "UpsertItemLink",
			Handler:    _JellyfinBridge_UpsertItemLink_Handler,
		},
		{
			MethodName: "DeleteItemLink",
			Handler:    _JellyfinBridge_DeleteItemLink_Handler,
		},
		{
			MethodName: "MatchItem",
			Handler:    _JellyfinBridge_MatchItem_Handler,
		},
		{
			MethodName: "SyncLibrary",
			Handler:    _JellyfinBridge_SyncLibrary_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _JellyfinBridge_ListSessions_Handler,
		},
		{
			MethodName: "TerminateSession",
			Handler:    _JellyfinBridge_TerminateSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/jellyfinv1/jellyfin.proto",
}
